name: CI Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
          - name: Checkout repository
            uses: actions/checkout@v2
  
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run Linter
            run:  python -m flake8 src

          - name: Setup mock database
            run: python setup_database.py

          - name: Run tests
            run: python -m pytest
          
          - name: Send Telegram Notification
            uses: appleboy/telegram-action@master
            with:
              to: ${{ secrets.TELEGRAM_TO }}
              token: ${{ secrets.TELEGRAM_TOKEN }}
              message: "Build completed successfully!"
          
          - name: Send Discord Notification
            env:
              DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
            run: |
              curl -H "Content-Type: application/json" \
              -d "{\"content\": \"Build completed successfully!\"}" \
              $DISCORD_WEBHOOK_URL
          
          - name: Deploy to Render
            uses: JorgeLNJunior/render-deploy@v1.4.4
            with:
              service_id: ${{ secrets.RENDER_SERVICE_ID }}
              api_key: ${{ secrets.RENDER_API_KEY }}
              github_token: ${{ secrets.CI_CD_TOKEN }}
