name: CI Pipeline

on:
    push:
        branches: [ main homologation ]
    pull_request:
        branches: [ main homologation ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
          - name: Checkout repository
            uses: actions/checkout@v2
  
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.11'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run Linter
            run:  python -m flake8 src

          - name: Setup mock database
            run: python setup_database.py

          - name: Run tests
            run: python -m pytest
          
          - name: Send Discord Notification
            uses: Ilshidur/action-slack@v2
            with:
              webhook-url: https://discord.com/api/webhooks/1256752114550440078/5JoEBkI2j52NiLpVjQDFaqwS5wwST1bdCIx8Yi5sz_EAxWfpbfz7-zSHp1exqdCEa-Sn
              msg: "Build completed successfully!"